name: code coverage

on:
  push:
    branches:
      - master
    paths:
      - 'source/DefaultUnDo/**'
      - 'source/DefaultUnDo.Test/**'

jobs:
  code_coverage:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Build netcoreapp3.0
      run: dotnet build source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f netcoreapp3.0

    - name: Install coverlet tool
      run: dotnet tool install --tool-path . --version 1.6.0 coverlet.console

    - name: Create coverage file
      run: dotnet .store\coverlet.console\1.6.0\coverlet.console\1.6.0\tools\netcoreapp2.2\any\coverlet.console.dll source\DefaultUnDo.Test\bin\Release\netcoreapp3.0\DefaultUnDo.Test.dll -t "dotnet" -a "vstest source\DefaultUnDo.Test\bin\Release\netcoreapp3.0\DefaultUnDo.Test.dll" -o coverage\lcov.info -f lcov

    - name: Upload to coverall
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
