name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - 'source/DefaultUnDo/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/Doraku/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Run tests net452
      run: dotnet test source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f net452

    - name: Run tests net48
      run: dotnet test source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f net48

    - name: Run tests netcoreapp3.0
      run: dotnet test source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f netcoreapp3.0

    - name: Create package
      run: dotnet pack source\DefaultUnDo\DefaultUnDo.csproj -c Release -o package -p:PackageReleaseNotes="${{ github.sha }}"

    - name: Publish package
      run: nuget push package\*.nupkg
