name: pull request

on:
  pull_request:
    paths:
      - 'source/**'

jobs:
  pull_request:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build
      run: dotnet build source -c Release -p:TreatWarningsAsErrors=true

    - name: Run tests net462
      run: dotnet test source -c Release -f net462 --no-build

    - name: Run tests net48
      run: dotnet test source -c Release -f net48 --no-build

    - name: Run tests net8.0
      run: dotnet test source -c Release -f net8.0 --no-build