name: pull request

on:
  pull_request:
    paths:
      - 'source/DefaultUnDo/**'
      - 'source/DefaultUnDo.Test/**'

jobs:
  pull_request:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'

    - name: Run tests net452
      run: dotnet test source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f net452

    - name: Run tests net48
      run: dotnet test source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f net48

    - name: Run tests netcoreapp3.0
      run: dotnet test source\DefaultUnDo.Test\DefaultUnDo.Test.csproj -c Release -f netcoreapp3.0